version: '3'

services:
  apt-cacher-ng:
    restart: unless-stopped
    image: sameersbn/apt-cacher-ng:latest
    platform: linux/arm/v7
    ports:
    - "3142:3142"
    volumes:
    - ./apt-cacher-ng:/var/cache/apt-cacher-ng
    networks:
      - unvt-pi-gen

networks:
  unvt-pi-gen:
    name: unvt-pi-gen
